name: Deploy website
on: push
jobs:
  Lint_Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  Build_Code:
    runs-on: ubuntu-latest
    needs: Lint_Code
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: dist
#          path: |
#            dist
#            package.json
  Deploy_Code:
    runs-on: ubuntu-latest
    needs: Build_Code
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
      - name: Output filename
        run: echo "${{ needs.Build_Code.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
