name: Event Details on Issue
on:
  issues:
    types:
      - opened
jobs:
  print_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
