name: Build and deploy project
on: push
jobs:
  Lint_Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        run: npm run lint
  Test_Code:
    runs-on: ubuntu-latest
    needs: Lint_Code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: npm run test
  Build_Code:
    runs-on: ubuntu-latest
    needs: Test_Code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: npm run build
